spring.application.name=foodify

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/foodify_db
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}